name: ostello
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  image_picker: 1.0.7
  path_provider: 2.1.2
  shared_preferences: 2.2.2
  http: 1.2.0
  auto_size_text: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
    - assets/
  fonts: 
    - family: Avenir
      fonts: 
        - asset: assets/fonts/Avenir.ttf
    - family: IngridDarling
      fonts: 
        - asset: assets/fonts/IngridDarling.ttf
  uses-material-design: true

